<a href="https://colab.research.google.com/github/lenn-dev/python/blob/main/numpy_basic%ED%98%81%ED%8E%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

모듈과 패키지
1. 모듈은 변수, 함수, 클래스를 담고 있는 파일 (.py)
2. 패키지는 여러 모듈을 묶은 것 (폴더)

- import 모듈1, 모듈2
- 모듈.변수
- 모듈.함수()
- 모듈.클래스()

In [2]:
import math
print(math.pi)
print(math.sqrt(4))

3.141592653589793
2.0


In [3]:
import math as m
print(m.pi)
print(m.sqrt(4))

3.141592653589793
2.0


In [4]:
from math import pi, sqrt
print(pi)
print(sqrt(4))

3.141592653589793
2.0


In [5]:
from math import *
print(pi)
print(sqrt(4))

3.141592653589793
2.0


In [6]:
# import 패키지
# import 패키지.모듈
# import 패키지.모듈1, 패키지.모듈2
# 패키지.모듈.변수
# 패키지.모듈.함수()
# 패키지.모듈.클래스()

In [7]:
import numpy as np # numpy는 라이브러리(패키지와 모듈을 모아놓음) numerical pyhon
a=np.array([1,2,3])
print(a)
type(np.array)

[1 2 3]


builtin_function_or_method

In [8]:
import numpy.random as r
print(r.randn(3,3)) #(3,3)은 3행3열의 배열(array) 생성
# 이 배열은 표준정규분포 (standard normal distribution)를 따르는 난수들로 채워짐
# 표준정규분포란 평균 0,표준편차가 1 인 분포이다.
# 즉, 각각의 값은 N(0,1)분포에서 임의로 뽑은 값

[[-0.76182654  1.55051883 -0.51071707]
 [-1.39033901  1.4244665  -0.63041667]
 [-0.36715591  0.35374942 -0.99847975]]


- iid(independent and identically distribued) 를 따르게끔
- 즉, 배열안의 각 원소들은 서로 독립적이며, 같은 분포에서 나왔다는 뜻
- 다시말해, 모든 값은 동일한 표준 정규분포 N(0,1)에서 독립적으로 추출된 것이다.
- 실행결과는 매번 달라진다.
- 무작위 데이터(random data)를 생성해 다양한 실험,테스트,시뮬레이션 하기 위한 것
- 머신러닝 모델에 입력하기 전에 작동 테스트용
- 확률적현상(예:주식가격변화, 센서노이즈, 물리모델 등)을 모델링 할 때 무작위 숫자 필요
- mesured_value = true_value + r.randn(3,3)*noise_level
- 통계개념(예:중심극한정리, 표본분포등)을 설명, 검증할 때 무작위 표본 필요
- 머신러닝/딥러닝 초기화: 신경망의 가중치를 무작위로 초기화할 때 자주 쓰임,
- 특히 표준 정규분포는 기초적인 초기화 방법중 하나

In [9]:
import numpy.random as nr
print(nr.randn(3,3))

[[-1.1532839   0.4108394   0.09774033]
 [ 0.41769429 -0.68575554 -0.10007978]
 [-0.70380772 -0.51448357  0.39873182]]


In [10]:
from numpy.random import randn
print(randn(3,3))

[[ 0.37639064 -0.22732335  1.06357086]
 [-0.23769913 -1.36364036  1.61984313]
 [ 0.78193499 -0.37285048  0.42882697]]


In [11]:
from numpy.random import *
print(rand(3,3)) #uniform distribution : 0과 1사이에서 균등한 분포

[[0.22199899 0.48493789 0.06355983]
 [0.4822433  0.5711356  0.07874747]
 [0.2468484  0.94786676 0.69441181]]


In [12]:
from numpy.random import randn as rn
print(rn(3,3))

[[ 0.98847794 -0.3586966  -0.89762679]
 [ 0.75685394 -0.06600895 -0.49209751]
 [-0.27164857  0.44145234  0.5704337 ]]


In [13]:
from numpy.random import randn as rn, rand as r
print(rn(3,3))
print(r(3,3))

[[-0.52178449  0.47749074  1.20627301]
 [-0.36264548  1.6743478   0.48929997]
 [-1.46426905 -0.40766704  1.93183183]]
[[0.90322671 0.72365486 0.61650792]
 [0.06452138 0.15597343 0.94312984]
 [0.71014893 0.12190924 0.89429635]]


# numpy 본격적으로

In [14]:
import numpy as np
a=np.array([1,2,3,4])# list 가 입력으로 들어가는 함수
print(a)
print(type(a))
print(a.dtype) # data type
print(a.ndim)
print(a.shape) # 각 차원 원소 갯수
print(a[0]) # 1로 출력됨
print(type(a[0]))

# 하나라도 실수이면 자동으로 모두 실수타입으로 바꿔줌
b=np.array([1,2, 3.1, 4]) # 하나만 소수점으로 바꿈
print(b)
print(b.dtype) # 리스트 안에 하나만 실수이면 다 실수타입으로 바껴서 각 숫자당 64비트로
print(b[0]) # 1.0이라고 출력됨 나옴
print(type(b[0])) # 리스트 첫번째원소 1도 float이라고 나옴


[1 2 3 4]
<class 'numpy.ndarray'>
int64
1
(4,)
1
<class 'numpy.int64'>
[1.  2.  3.1 4. ]
float64
1.0
<class 'numpy.float64'>


In [15]:
A=np.array([[1,2],[3,4]])
#A=np.array([[1,2],[3,4,5]]) # 갯수가 다름
# 리스트와 달리 이제는 행렬이라 각 행에 해당하는 숫자의 갯수가 같아야 함
print(A)
print(A.shape) # 2행2열  제일 많이 씀
print(A.ndim) # 차원의 수, 대괄호가 몇개인가, 2차원
# 차원이 묶여있다. 2차원 공간에 사이즈가 같은 큐브가 묶여있다.
# 3차원은 묶여있는것이 깊이있게 쌓여있다.
# 4차원은 3차원으로 쌓여있는 것이 여러개인 것이 주머니에 담겨있다.
# 5차원은 가방에 그런 주머니가 여러개 있다.
# 6차원은 방 안에 그런 가방이 여러개 있다.
# 7차원은 그 방이 여러개 있다.
print(A.size) # 전체 성분의 수 == A.shape[0]* A.shape[1]
# 2행 2열이니 2*2 한 것인데, 곱하기로 표현하기 번거로우니 size로 함


[[1 2]
 [3 4]]
(2, 2)
2
4


In [16]:
#0으로 초기화
print(np.zeros(10)) # 10 벡터 생성
print(np.zeros_like(A)) # A의 사이즈를 그대로 가져와서 0으로 채운 행렬 만들어줌
print(np.ones_like(A))
print(np.zeros((3,4))) # 3행4열 행렬로 만들어 주고 싶을 때는 리스트나 튜플로 묶어 하나로 줘야 함
# np.zeros(3,3)은 안됨

# torch 에서는 됨.
import torch
print(torch.zeros(3,3))

print(np.arange(3,10,2)) # range랑 같은데 array이로 만들어줌
print(np.arange(0,1,0.1)) # 0부터 1미만 0.1 간격
print(np.linspace(0,1,10, endpoint=False)) # 0부터 1 포함 10개로 선형적으로 쪼갬
# 1을 포함하지 않는 endpoint=False 조건넣으면 위와 같은 결과가 나옴

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0 0]
 [0 0]]
[[1 1]
 [1 1]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
[3 5 7 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [17]:
# 벡터의 합
a=np.array([1,2,3])
b=np.array([4,5,6])
c= a+b
print(c)
# 리스트는 값을 쌓아주기만 함
[1,2,3]+[4,5,6]

[5 7 9]


[1, 2, 3, 4, 5, 6]

In [18]:
# np.array를 이용한 행렬 만들기 -> 리스트 속에 리스트
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[1,2,3],[4,5,6]])
print(A+B)
print(A-B)
print(A*B) # 곱셉은? 성분끼리의 곱 (Hadamard product)
print(A/B) # 나누기? 성분끼리의 나누기 (이 경우 정사각행렬이 아니라 역행렬이 존재하지도 않음)
print(B**2) # 제곱? 성분에 대한 제곱


[[ 2  4  6]
 [ 8 10 12]]
[[0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[ 1  4  9]
 [16 25 36]]


In [19]:
# 행렬곱
A=np.array([[1,2],[3,4]])
B=np.array([[1,2],[3,4]])
print(A*B)
#print(np.matmul(A,B)) # 행렬곱
print(A@B) # 행렬곱

[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


In [20]:
#numpy 의 인덱싱과 슬라이싱: 리스트와 차이 없음
a=np.array([1,2,3,4])
print(a[0])
print(a[-1])
print(a[1:3])
print(a[1:])
print(a[:3])
print(a[:])

1
4
[2 3]
[2 3 4]
[1 2 3]
[1 2 3 4]


In [21]:
# 행렬에 대한 인덱싱 슬라이싱: 리스트와 차이점
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A[0])
print(A[-1])
print(A[1:])
print(A[:])
print(A[0][2])
print(A[0,2]) # 콤마로 해도 numpy에서는 지원해줌 (리스트에선 안됨)
print(A[0,])
print(A[0,:]) #위와 같음
print(A[0,0:3:2]) # 첫번째 행, 열은 0부터3미만까지 2간격
print(A[:,0])
print(A[:,2])

[1 2 3]
[7 8 9]
[[4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
3
[1 2 3]
[1 2 3]
[1 3]
[1 4 7]
[3 6 9]


In [22]:
# boolean 인덱싱
# a 리스트의 3을 100으로 바꾸고 싶을 때
a = [1,2,3,4]
a == 3 # 이런 표현은 a리스트와 3이 같냐고 묻는것이므로 의도한 바가 아님

A=np.array([[1,2,3,4],[3,5,6,4]])
print(A==3) # 리스트와 달리 각 요소에 대해 비교해줌
# True,False 가 담긴 행렬로 인뎅싱 가능
# 인뎅싱하는 []대괄호 안에 boolean 을 넣어주면 됨
A[A==3]=100
print(A)

A=np.array([[1,2],[3,4],[5,6],[7,8]])
B=np.array([True,False,True,False])
print(A[B])

b=[True,False,True,False] # 리스트여도 같은 결과
print(A[b])

[[False False  True False]
 [ True False False False]]
[[  1   2 100   4]
 [100   5   6   4]]
[[1 2]
 [5 6]]
[[1 2]
 [5 6]]


In [23]:
# 3차원 행렬 인덱싱
A=np.array([[[0,1,2,3],[4,5,6,7],[8,9,10,11]],
            [[12,13,14,15],[16,17,18,19],[20,21,22,23]]])

print(A)
print(A.shape) #3행4열짜리
print(A[0,1,2])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
6


In [24]:
# numpy 의 여러 함수들
A=np.random.randn(3,3) #zeros는 튜플로 줘야 하는데 여긴 튜플로 안줘도 됨
B=np.random.rand(3,3)
print(A)
#print(B)
# boolean 조건문 복습
print(A[A[:,0]<0,:]) # 0번째 열이 음수인 행을 가져옴

[[ 1.86295353  0.28136265 -0.02125416]
 [-0.75248232  0.25433016  1.15463725]
 [ 2.17518713 -1.23498995 -0.30251784]]
[[-0.75248232  0.25433016  1.15463725]]


In [25]:
A=np.random.randn(3,3)
print(A)
print(np.abs(A)) # 절대값
print(np.sqrt(np.abs(A)))
print(np.exp(A))
print(np.log(np.abs(A))) # 로그도 음수 들어가면 안되니 절대값먼저 하고 로그
print(np.exp(1)) # = e^1
print(np.log(np.exp(1)))
print(np.log2(2))
print(np.log10(10))
print(np.round(A)) # 반올림
print(np.round(A,2)) # 소숫점 둘째자리까지 올림
print(np.floor(A)) # 내림
print(np.ceil(A)) # 올림

[[-1.21449849  2.02985196 -0.70014622]
 [ 0.93298196  0.40034313  0.61072758]
 [ 0.68324945  0.75648366 -0.61089972]]
[[1.21449849 2.02985196 0.70014622]
 [0.93298196 0.40034313 0.61072758]
 [0.68324945 0.75648366 0.61089972]]
[[1.10204287 1.42472873 0.83674741]
 [0.96590991 0.63272674 0.78149061]
 [0.82658905 0.86976069 0.78160074]]
[[0.29685885 7.61295924 0.4965127 ]
 [2.54207827 1.49233668 1.84177094]
 [1.98030219 2.13077052 0.54286223]]
[[ 0.19433123  0.70796286 -0.35646608]
 [-0.06936941 -0.91543327 -0.49310428]
 [-0.38089526 -0.27907434 -0.49282246]]
2.718281828459045
1.0
1.0
1.0
[[-1.  2. -1.]
 [ 1.  0.  1.]
 [ 1.  1. -1.]]
[[-1.21  2.03 -0.7 ]
 [ 0.93  0.4   0.61]
 [ 0.68  0.76 -0.61]]
[[-2.  2. -1.]
 [ 0.  0.  0.]
 [ 0.  0. -1.]]
[[-1.  3. -0.]
 [ 1.  1.  1.]
 [ 1.  1. -0.]]


In [26]:
# numpy 안의 sin,cos,tan 과 pi
print(np.sin(np.pi/6))
print(np.cos(np.pi/6))
print(np.tan(np.pi/6))
print(np.tanh(-10))

0.49999999999999994
0.8660254037844387
0.5773502691896257
-0.9999999958776927


In [27]:
#np.nan # not a number
#np.log(-1) # 들어가면 안되는 음수 넣으면 에러메시지 nan 이 뜸
# 체크해주기 위해 isnan
print(np.isnan([1,2,np.nan,3,4]))
print(np.isinf([1,2,3,4,np.inf]))

[False False  True False False]
[False False False False  True]


In [28]:
# 분포를 알기 위한 것
#max
A=np.random.randn(3,4)
print(A)
print(np.max(A))
print(np.max(A,axis=0))
# axis=0은 "행을 따라", 즉 열(column)끼리 비교한다는 거야.
#축 개념:
#axis=0 → 세로 방향 비교 (같은 열끼리)
#axis=1 → 가로 방향 비교 (같은 행끼리)
print(np.max(A,axis=1))
# 3열처럼 나와서 가로비교한 행 결과로 유지하고 싶으면
print(np.max(A,axis=1,keepdims=True)) #3행1열
print(np.max(A,axis=0,keepdims=True)) #1행4열

#min
print(np.min(A,axis=0,keepdims=True))

#argmin, argmax : max,min 값의 인덱스 반환함
print(np.argmax(A))
print(np.argmin(A))

[[-0.33455837  0.08139904  1.22802219  0.40613731]
 [-0.3078609   0.43614454  0.201413    0.01035949]
 [-1.41540341  1.26657555  1.25978956  1.40561091]]
1.405610914463996
[-0.3078609   1.26657555  1.25978956  1.40561091]
[1.22802219 0.43614454 1.40561091]
[[1.22802219]
 [0.43614454]
 [1.40561091]]
[[-0.3078609   1.26657555  1.25978956  1.40561091]]
[[-1.41540341  0.08139904  0.201413    0.01035949]]
11
8


In [29]:
a=np.random.randn(6,1)
print(a)
a_sorted=np.sort(a,axis=0) # sort()사용해 정렬
print(a_sorted) # 오름차순
print(np.flipud(a_sorted)) #위아래로 뒤집어 flip up down 내림차순으로 바꿈


[[-0.20482777]
 [-0.63399272]
 [ 0.69161706]
 [-0.0745798 ]
 [-0.98185008]
 [ 1.05163418]]
[[-0.98185008]
 [-0.63399272]
 [-0.20482777]
 [-0.0745798 ]
 [ 0.69161706]
 [ 1.05163418]]
[[ 1.05163418]
 [ 0.69161706]
 [-0.0745798 ]
 [-0.20482777]
 [-0.63399272]
 [-0.98185008]]


In [30]:
A=np.random.randn(3,4)
print(A)
print(np.sum(A))
print(np.sum(A,axis=1))
print(np.sum(A,axis=1,keepdims=True)) #3행1열짜리 2d array
print(np.mean(A))
print(np.mean(A,axis=1))
print(np.sum(A,axis=1,keepdims=True))
print(np.std(A)) #standard deviation 표준편차

[[-0.11703146 -1.14530759 -0.5196557  -1.51172212]
 [-3.19588667  0.01785561  0.16703896  0.71897753]
 [ 1.72236513  1.45321391 -0.6145409  -0.00708825]]
-3.0317815514829207
[-3.29371688 -2.29201456  2.55394989]
[[-3.29371688]
 [-2.29201456]
 [ 2.55394989]]
-0.2526484626235767
[-0.82342922 -0.57300364  0.63848747]
[[-3.29371688]
 [-2.29201456]
 [ 2.55394989]]
1.269176929535876


In [31]:
A=np.random.randint(-2,5,size=(12,)) # -2부터 5 미만까지 랜덤정수 12개
print(A)
print(A.shape)
B=A.reshape(2,2,3) # 2행3열 2개 짜리고 reshape 하기
print(B)
print(B.ndim) #3차원 행렬이다. [[[]]]

[ 1  1  1  4  1  1 -1  2  3  3  0 -2]
(12,)
[[[ 1  1  1]
  [ 4  1  1]]

 [[-1  2  3]
  [ 3  0 -2]]]
3


In [32]:
# 내적 표현
# a,b 내적해서 합인 9 구하기
a=np.array([1,2,3])
b=np.array([2,2,1])
print(a)
print(b)
print(np.sum(a*b))
print(a@b)#1차원은 벡터가 아니라 내적이라 할 수 없지만 에러는 안남
# 이 방법은 array 원소수가 다르면 에러남

#열벡터로 바꾼 뒤 하나는 전치시켜서 행렬곱 @ 적용하는 방법
a= a.reshape(3,1)
b= b.reshape(3,1)
print(a)
print(b)
print(np.sum(a.T@b))
print(np.sum(a.transpose()@b))

# 3D에서 T 활용
A=np.random.randn(2,3,4)
#print(A)
#print(A.T)
print(A.transpose(0,1,2).shape) # 그대로 나옴 0번째
print(A.transpose(2,1,0).shape) # 뒤집어진 shape으로 나옴
print(A.transpose(2,0,1).shape)

[1 2 3]
[2 2 1]
9
9
[[1]
 [2]
 [3]]
[[2]
 [2]
 [1]]
9
9
(2, 3, 4)
(4, 3, 2)
(4, 2, 3)


In [33]:
A=np.arange(20)
print(A)
print(A.reshape(4,5)) # 4,하면 무조건 5여야 사이즈가 맞지만,
print(A.reshape(4,-1)) # -1 을 뒤에 쓰면, 4개 행이 되도록 열의 수를 맞춰줌
print(A.reshape(2,-1)) #-1 은 알아서 채워줌

# -1 이용해서 2차원 행벡터, 열벡터 쉽게 만들기
print(A.reshape(1,-1)) # 2차원 행 벡터
print(A.reshape(-1,1)) # 2차원 열 벡터

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]]


In [34]:
# 고차원 슬라이싱
x=np.random.randn(2,3,4,5,6) # 5차원배열, 5개의 축
#x
#└── 2개의 블록 (axis=0)
#    └── 각 블록은 3개의 서브블록 (axis=1)
#        └── 각 서브블록은 4개의 배열 (axis=2)
#            └── 각 배열은 5개의 벡터 (axis=3)
#                └── 각 벡터는 길이 6 (axis=4)

print(x[1,2,:,:,:].shape)

# x[1, 2, :, :, :]  == x[1, 2]

#axis=0: 인덱스 1 선택 (두번째 블록 선택)
#axis=1: 인덱스 2 선택 (세번째 서브블록 선택)
#axis=2,3,4: 전체 다 (:)
#즉, 앞의 두 축(2개 차원)을 "숫자 인덱스로 고정"하고, 뒤의 3개 차원은 그대로 유지.
#즉, 숫자를 사용하면 그 차원은 사라지고, :을 사용하면 그 차원은 유지됨.

#전체 x는 이렇게 생겼다고 상상해봐:
#x → (2 blocks)
#    └── each block: (3 items)
#        └── each item: shape (4, 5, 6)
#x[1, 2] → 이건 결국 그 중 한 덩어리만 딱 집은 거야.
#그리고 그 덩어리는 shape (4, 5, 6)이니까 그게 남는 거지.

#x.shape = (2, 3, 4, 5, 6)

#x[1]           → shape (3, 4, 5, 6)
#x[1, 2]        → shape (4, 5, 6)     ✅ "덩어리 하나"
#x[1, 2, :, :, :] → shape (4, 5, 6)  ⬅️ 같은 표현, 명시적으로 쓴 것

print(x[1,2,...].shape) # print(x[1,2,:,:,:].shape) 과 같음

print(x[:,:,:,:,3].shape)
print(x[...,3].shape)
print(x[1,:,:,3,:].shape)
print(x[1,...,3,:].shape)

(4, 5, 6)
(4, 5, 6)
(2, 3, 4, 5)
(2, 3, 4, 5)
(3, 4, 6)
(3, 4, 6)



---

## 🎯 왜 축 고정 + shape 확인이 중요할까?

### 핵심은:

> **"원하는 데이터 구조만 남겨서 정확히 다루기 위해서야."**

고차원 데이터를 다룰 때, 어떤 축을 **인덱싱해서 없애거나**, 어떤 축을 **슬라이싱해서 유지할지** 결정하는 건
→ 모델에 넣기 전 **shape이 원하는 대로 맞는지**
→ 수학 연산이 **브로드캐스팅 가능한지**
→ 데이터 전처리에서 **특정 위치 정보만 추출할지**
를 정확히 알기 위해서야.

---

## 📌 어디서 자주 쓰이냐면?


### 1. 📊 머신러닝/딥러닝에서 배치 처리

#### 예: CNN 입력 데이터

```python
images = np.random.randn(32, 3, 64, 64)  # (batch, channel, height, width)
```

이럴 때:

* `images[0]` → 한 장의 이미지 선택 → shape: `(3, 64, 64)`
* `images[:, 0]` → 모든 배치에서 첫 번째 채널만 추출 → shape: `(32, 64, 64)`

👉 축을 고정하고 나머지를 슬라이싱하면, 원하는 구조를 뽑아낼 수 있음.

---


### 2. 🧠 AI 모델에서 Attention이나 Embedding 계산 시

```python
x = np.random.randn(batch, seq_len, hidden_dim)  # (32, 128, 512)
```

* `x[:, 0, :]` → 각 문장에서 첫 번째 토큰의 embedding만 추출

  * shape: `(32, 512)` ← 축 하나 줄어듦
* `x[:, :, 0]` → 각 토큰의 embedding에서 첫 번째 feature만 추출

  * shape: `(32, 128)`

👉 이걸로 "특정 토큰"이나 "특정 feature"에만 연산 집중 가능.

---


### 3. 📐 선형대수에서 벡터/행렬 연산

#### 예: 행렬 곱 (dot product)

```python
A = np.random.randn(10, 20)
B = np.random.randn(20, 30)

result = np.dot(A, B)  # shape: (10, 30)
```

근데 `A[0]`은?

→ shape: `(20,)`
→ `np.dot(A[0], B)` → shape: `(30,)` ← 한 줄(row)에 대한 연산만 수행 가능

👉 특정 행만 뽑아서 따로 연산할 때 축을 고정함.

---


### 4. 🧪 과학/이미지 데이터 처리에서

예: 의료 영상 (CT, MRI)은 3D 이상으로 다뤄짐

```python
scan = np.random.randn(30, 256, 256)  # (slice, height, width)
```

* `scan[15]` → 16번째 단면 이미지 추출 → shape: `(256, 256)`
* `scan[:, 128, 128]` → 모든 슬라이스에서 특정 위치의 값만 추출 → shape: `(30,)`

👉 특정 축을 인덱싱해서 의미 있는 데이터만 추출해야 하는 상황

---


## 💡 그래서 정리하면

| 상황    | 축 고정 인덱싱이 필요한 이유     |
| ----- | -------------------- |
| 모델 학습 | 입력 텐서의 shape 맞추기     |
| 전처리   | 특정 위치/feature/토큰만 추출 |
| 선형대수  | 벡터·행렬 연산 준비          |
| 시각화   | 2D로 slice 잘라보기       |
| 디버깅   | shape 찍어보고 연산 오류 확인  |

---

## 🚧 만약 shape 확인을 안 하고 쓴다면?

* **모델 입력 shape mismatch 에러**
* **Broadcasting 실패**
* **차원 불일치로 연산 오류**
* 혹은 결과는 나오지만 **의미 없는 결과**

→ 그래서 **고정하고 shape 확인하는 습관이 안전망이자 최적화의 시작**이야.

---

필요하면 위 예제 중 하나로 직접 실습 코드 같이 짜볼 수도 있어!
PyTorch나 TensorFlow로도 예시 보여줄 수 있고!

더 궁금한 분야 (예: NLP, 이미지, 모델 구조 등) 있으면 거기 맞춰 더 깊이 설명해줄게 😎


좋아, 이제 진짜 실전 예시로 넘어가보자.
PyTorch랑 TensorFlow 두 가지 다 보여줄게 — 비교도 쉽도록 똑같은 구조로 설명할게!

🎯 목표
배치 데이터 중 하나의 샘플만 추출하거나, 특정 축을 고정해 연산하는 실제 예


우선 공통적인 전제:
```
# 공통 텐서 구조: (batch, channel, height, width)
# 이미지 데이터 (예: RGB 이미지 32장, 3채널, 64x64 사이즈)
```


# 🟠 PyTorch 예시
```
import torch

# (batch_size=32, channels=3, height=64, width=64)
x = torch.randn(32, 3, 64, 64)

# ✅ 1. 배치 중 첫 번째 이미지 가져오기
img = x[0]                # shape: (3, 64, 64)
print("img.shape:", img.shape)

# ✅ 2. 각 이미지에서 첫 번째 채널만 추출
first_channel = x[:, 0, :, :]  # shape: (32, 64, 64)
print("first_channel.shape:", first_channel.shape)

# ✅ 3. 각 이미지의 (32,32) 위치에 있는 RGB 픽셀값만 추출
pixel_values = x[:, :, 32, 32] # shape: (32, 3)
print("pixel_values.shape:", pixel_values.shape)

# ✅ 4. 단일 이미지의 평균값
mean_pixel = img.mean()        # 모든 픽셀 평균값 (스칼라)
print("mean_pixel:", mean_pixel.item())
```


# 🔵 TensorFlow 예시
```
import tensorflow as tf

# (batch_size=32, channels=3, height=64, width=64)
# TF 기본 순서는 (batch, height, width, channels) 이지만, 여기선 비교 위해 동일하게 설정
x = tf.random.normal((32, 3, 64, 64))

# ✅ 1. 배치 중 첫 번째 이미지 가져오기
img = x[0]                # shape: (3, 64, 64)
print("img.shape:", img.shape)

# ✅ 2. 각 이미지에서 첫 번째 채널만 추출
first_channel = x[:, 0, :, :]  # shape: (32, 64, 64)
print("first_channel.shape:", first_channel.shape)

# ✅ 3. 각 이미지의 (32,32) 위치에 있는 RGB 픽셀값만 추출
pixel_values = x[:, :, 32, 32] # shape: (32, 3)
print("pixel_values.shape:", pixel_values.shape)

# ✅ 4. 단일 이미지의 평균값
mean_pixel = tf.reduce_mean(img)
print("mean_pixel:", mean_pixel.numpy())
```

💡 실전에서 이게 왜 중요하냐면:
작업	축 고정 이유
모델 디버깅	특정 이미지 하나만 확인하고 싶을 때 → x[0]
feature 시각화	첫 번째 채널만 봐야 할 때 → x[:, 0, :, :]
attention 연산	시퀀스 중 특정 토큰만 뽑기 → x[:, 0, :]
선형변환 전처리	특정 위치 벡터 추출 → x[:, :, i, j]
학습 전 분석	입력 한 장의 통계값(mean, std 등) 확인

📌 참고: TensorFlow는 순서가 다르다
TensorFlow는 기본적으로 NHWC 형식이야:

```
TF 기본 순서: (batch, height, width, channels)
PT 기본 순서: (batch, channels, height, width)
```
그래서 실제 프로젝트에선 TensorFlow 코드라면 보통 아래처럼 생겼어:

```
x = tf.random.normal((32, 64, 64, 3))  # (B, H, W, C)
x[:, 32, 32, :]  # shape: (32, 3) ← 32x32 위치의 RGB
```
→ 꼭 framework의 차원 순서 (data format) 를 기억해야 함!

필요하면 Transformer 모델, RNN 시퀀스 예시, 1D conv, NLP attention 등 고급 예시도 보여줄 수 있어!
어떤 쪽이 네가 공부 중인 방향이랑 맞아? 더 깊게 들어가자 😎

In [35]:
A=np.ones((2,2))
B=np.zeros((2,2))
C=np.hstack([A,B]) #horizontal stack 가로로 쌓기
print(A)
print(B)
print(C)
D=np.vstack([A,B]) #vertical stack 세로로 쌓기
print(D)
E=np.block([A,B]) # 내 마음대로 쌓기
F=np.block([[A],[B]])
print(E)
print(F)
G=np.block([[[A]],[[B]]])
print(G)
print(G.shape)

[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 1. 0. 0.]
 [1. 1. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 0. 0.]
 [1. 1. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]
[[[1. 1.]
  [1. 1.]]

 [[0. 0.]
  [0. 0.]]]
(2, 2, 2)


In [36]:
# 1차원이 겹겹이 있을 때 squeeze로 정리하기
A = np.random.randn(1,1,1,3,1,1,4,1) # 1이 쓸데없이 많을 때, 정작 3행4열에 위치하는 것
print(A)
# 이를 정리해주는 방법이 squeeze
print(np.squeeze(A).shape) # 1은 다 없애줌
# 내가 원하는 1만 없애고 싶을 때
print(A.squeeze().shape)
print(A.squeeze(axis=(0,2,4,5)).shape)  # 없애고 싶은 곳의 axis 적어줌


[[[[[[[[-2.00636612]
       [ 1.58909618]
       [ 1.33552506]
       [-0.89005448]]]]



    [[[[ 1.66499148]
       [-0.97233535]
       [-1.17492519]
       [ 0.05371511]]]]



    [[[[ 0.54901356]
       [ 0.69166368]
       [-1.291869  ]
       [-0.33379046]]]]]]]]
(3, 4)
(3, 4)
(1, 3, 4, 1)


In [38]:
# 새로운 축 만들기
A=np.random.randn(3,4)
A1=A[np.newaxis,...] #np.newaxis is None <-True
print(A1.shape)
A2 = A[...,np.newaxis]
print(A2.shape)
A3 =A[:,np.newaxis,:]
print(A3.shape)
# expand_dims  위와 같은 결과 다르게 추가하기
A1=np.expand_dims(A,axis=0)
print(A1.shape)
A2=np.expand_dims(A,axis=2)
print(A2.shape)
A3=np.expand_dims(A,axis=1)
print(A3.shape)
#reshape으로 같은결과
A1=A.reshape(1,3,4)
print(A1.shape)
A2=A.reshape(3,4,1)
print(A2.shape)
A3=A.reshape(3,1,4)
print(A3.shape)

(1, 3, 4)
(3, 4, 1)
(3, 1, 4)
(1, 3, 4)
(3, 4, 1)
(3, 1, 4)
(1, 3, 4)
(3, 4, 1)
(3, 1, 4)
